// data generated by the Sensor Plugin
data = fscanfMat("history.txt");
l = size(data, 1);

// time modulus x y z
for k = 1:l
    sleep(100);
    x = [0; data(k,3)];
    y = [0; data(k,4)];
    z = [0; data(k,5)];
    plot3d(x, y, z);
    set(gca(),'grid',[1 1]);
    title('Sensor Plugin');
end
